insert into SNS_ACCOUNT(ID, REAL_NAME, NICKNAME, EMAIL, SNS_ID, SNS_DOMAIN, CREATED_TIME, UPDATED_TIME)
values ('1', '남상엽', 'leaf', 'leaf@example.com', 'SNS_ID', 'KAKAO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
