insert into AAR_USER(ID, REAL_NAME, PHONE_NUMBER, NICKNAME, EMAIL, TERMS_OF_USE_AGREEMENT,
                     PERSONAL_INFORMATION_AGREEMENT, CREATED_TIME, UPDATED_TIME)
values (1, null, 'NOT_SET', 'leaf', 'test@example.com', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


insert into BUSINESS_USER(ID, EMAIL, PASSWORD, NICKNAME, STATUS, TERMS_OF_USE_AGREEMENT, PERSONAL_INFORMATION_AGREEMENT,
                          CREATED_TIME, UPDATED_TIME, USER_ID)
values (1, 'test@example.com', '{bcrypt}$2a$10$E4pJtJxQtjHHH11j8/tNTOJljXDFJc3NWGlbCt00SZQB8Nn7DiKF.', 'temp_user123',
        'WAITING', true, true, '2025-06-27 20:15', '2025-06-27 20:15', 1);
